Estilo sumo primero
eol-uchile/cmm-theme pull request #41
Opened 2024-09-12 16:15 UTC by Lozamded

Se reordena el archivo sass y se añaden elementos para el estilo de los nuevos cursos de sumo primero

2024-10-03 16:33 UTC, fsologureng requested changes

2024-10-03 16:33 UTC, fsologureng commented on cms/static/sass/_overrides.scss
> +    background-image: url('data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAFoAAABsCAYAAADqi6WyAAABHmVYSWZJSSoACAAAAAsAAAEEAAEAAABaAAAAAQEEAAEAAABsAAAAAgEDAAMAAACSAAAADgECAAsAAACYAAAAEgEDAAEAAAABAAAAGg
Cambiar por imagen en disco y referencia. Base64 es muy ineficiente en la transferencia y esto afecta a todo nuestro cluster.

2024-10-03 16:33 UTC, fsologureng commented on lms/static/sass/_overrides.scss
> +  background-image: url('data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAFoAAABsCAYAAADqi6WyAAABHmVYSWZJSSoACAAAAAsAAAEEAAEAAABaAAAAAQEEAAEAAABsAAAAAgEDAAMAAACSAAAADgECAAsAAACYAAAAEgEDAAEAAAABAAAAGgEF
Ídem anterior.

2024-10-03 16:37 UTC, fsologureng commented
@Lozamded adicionalmente a los cambios pedidos en el review, hay un problema con la rama master en cmmedu: el merge commit del pr #40 no debería ser parte de los commits de este PR pues ya está en nuestra rama master.
Aparentemente hace falta hacer un rebase en vuestra rama. Deben resolverlo.

2024-10-04 15:52 UTC, Lozamded commented
Hola por un tema de orden hicimos otro pull request con los cambios mas limpios 
https://github.com/eol-uchile/cmm-openedx/pull/42
este repo tambien ha sido probado en nuestros entronos de prueba

2024-10-04 15:52 UTC, closed without merging